import { CheckCircle2, TriangleAlert } from "lucide-react";
import { TaxConfigurationData } from "../OnboardingFlow";

interface TaxConfigurationStepProps {
  onBack: () => void;
  onNext: () => void;
  onSkip: () => void;
  data: TaxConfigurationData;
  onChange: (data: TaxConfigurationData) => void;
}

function TaxOption({
  title,
  subtitle,
  badge,
  active,
  recommended,
  onSelect,
}: {
  title: string;
  subtitle: string;
  badge: string;
  active?: boolean;
  recommended?: boolean;
  onSelect: () => void;
}) {
  return (
    <button
      type="button"
      onClick={onSelect}
      className={`w-full rounded-[12px] border-2 p-4 text-left transition-all ${
        active
          ? "border-[#5cc7eb] bg-[#f0faff] shadow-sm shadow-[#5cc7eb]/20"
          : "border-slate-200 bg-white hover:border-[#5cc7eb]/50 hover:bg-slate-50"
      }`}
    >
      <div className="flex items-start justify-between gap-3">
        <div className="flex items-start gap-3">
          <div
            className={`mt-0.5 h-5 w-5 shrink-0 rounded-full border-2 flex items-center justify-center transition-all ${
              active ? "border-[#5cc7eb] bg-[#5cc7eb]" : "border-slate-300"
            }`}
          >
            {active && <CheckCircle2 size={12} className="text-white" />}
          </div>
          <div>
            <div className="text-[15px] font-bold text-slate-800">{title}</div>
            <div className="text-[12px] mt-0.5 text-slate-500">{subtitle}</div>
          </div>
        </div>
        <div className="flex flex-col items-end gap-1 shrink-0">
          {recommended && (
            <span className="text-[9px] uppercase tracking-[0.16em] px-2 py-0.5 rounded-full bg-[#bdefff] text-[#0c607b] font-bold">
              Recommended
            </span>
          )}
          <span className="text-[10px] px-2 py-0.5 rounded-full bg-slate-100 text-slate-500 font-semibold">
            {badge}
          </span>
        </div>
      </div>
    </button>
  );
}

export function TaxConfigurationStep({
  onBack,
  onNext,
  onSkip,
  data,
  onChange,
}: TaxConfigurationStepProps) {
  const isInclusive = data.taxMode === "INCLUSIVE";
  const isExclusive = data.taxMode === "EXCLUSIVE";

  // Next is always enabled — INCLUSIVE doesn't need a rate input
  // EXCLUSIVE requires a valid rate > 0
  const nextEnabled = isInclusive || (isExclusive && Number(data.taxRate || 0) > 0);

  const updateMode = (taxMode: TaxConfigurationData["taxMode"]) => {
    onChange({
      ...data,
      taxMode,
      taxRate: taxMode === "INCLUSIVE" ? "10" : data.taxRate || "10",
    });
  };

  // Preview calculations
  const taxRateVal = Number(data.taxRate || 10);
  const previewItemTotal = 10.0;

  // EXCLUSIVE: subtotal = $10, GST added on top
  const exclusiveGst = previewItemTotal * (taxRateVal / 100);
  const exclusiveTotal = previewItemTotal + exclusiveGst;

  return (
    <section>
      <h1 className="text-[34px] sm:text-[52px] font-extrabold text-[#0b1324] leading-[1.05] tracking-[-0.02em]">
        Configure your Tax settings
      </h1>
      <p className="text-slate-600 mt-3 text-[15px]">
        Choose how GST is applied to your prices. This affects all bills
        generated by the system.
      </p>

      <div className="mt-8 rounded-[16px] border border-slate-200 bg-white p-5 sm:p-8">
        <div className="grid lg:grid-cols-[1fr_220px] gap-8">
          <div className="space-y-4">
            {/* Option 1 — GST Included */}
            <TaxOption
              title="GST included in price"
              subtitle="Prices already include GST. No extra tax is added at checkout. Standard Australian practice."
              badge="Australian Standard"
              active={isInclusive}
              recommended
              onSelect={() => updateMode("INCLUSIVE")}
            />

            {/* Option 2 — GST Added on Top */}
            <TaxOption
              title="GST added on top"
              subtitle="GST is calculated separately and added to the subtotal at checkout."
              badge="Tax Exclusive"
              active={isExclusive}
              onSelect={() => updateMode("EXCLUSIVE")}
            />

            {/* Tax Rate Input — only for EXCLUSIVE */}
            {isExclusive && (
              <div className="mt-2 ml-1 max-w-[240px] animate-in fade-in slide-in-from-top-2 duration-200">
                <label className="text-[11px] font-bold text-slate-600 uppercase tracking-widest">
                  GST Rate (%)
                </label>
                <div className="mt-2 flex items-center gap-2">
                  <input
                    type="number"
                    min={0}
                    max={100}
                    step="0.01"
                    value={data.taxRate}
                    onChange={(e) =>
                      onChange({ ...data, taxRate: e.target.value })
                    }
                    className="h-11 w-full rounded-[10px] border border-slate-200 bg-[#f8fafc] px-4 text-[15px] font-bold text-slate-800 outline-none focus:border-[#5cc7eb] focus:ring-2 focus:ring-[#5cc7eb]/20 transition"
                    placeholder="10"
                    aria-label="GST tax rate"
                  />
                  <span className="text-[18px] font-black text-slate-400">%</span>
                </div>
                <p className="text-[10px] mt-1.5 text-slate-400">
                  Standard Australian GST is <strong>10%</strong>
                </p>
              </div>
            )}

            {/* Info notice */}
            <div className="mt-3 rounded-[10px] border border-[#f6de9e] bg-[#fff7df] p-3 max-w-[420px]">
              <div className="flex items-start gap-2">
                <TriangleAlert size={14} className="text-[#d98700] mt-0.5 shrink-0" />
                <div>
                  <div className="text-[11px] font-bold text-[#8a5e00]">
                    Important: Finalize carefully
                  </div>
                  <div className="text-[10px] text-[#ad7a0d] mt-0.5">
                    These settings affect every bill generated. Only admins can
                    change this later in Settings.
                  </div>
                </div>
              </div>
            </div>
          </div>

          {/* Receipt Preview */}
          <div className="rounded-[14px] bg-[#020819] text-white p-4 shadow-2xl shadow-black/40 max-w-[220px] w-full mx-auto flex flex-col min-h-[300px]">
            <div className="text-[9px] uppercase tracking-[0.15em] text-slate-400 mb-5">
              Receipt Preview
            </div>

            {/* Store name */}
            <div className="text-[11px] text-slate-300 font-semibold">Signature Coffee</div>
            <div className="mt-2 h-px bg-white/10" />

            {/* Items */}
            <div className="mt-3 space-y-1">
              <div className="flex justify-between text-[10px] text-slate-400">
                <span>Flat White × 1</span>
                <span>$10.00</span>
              </div>
            </div>

            <div className="mt-3 h-px bg-white/10" />

            {isInclusive ? (
              /* ── INCLUSIVE: Just total + "GST included" note ── */
              <>
                <div className="mt-3 flex justify-between text-[13px] font-bold text-white">
                  <span>Total</span>
                  <span className="text-[#30b7ff]">$10.00</span>
                </div>
                <div className="mt-2 rounded-[6px] bg-white/5 px-2.5 py-1.5 text-center">
                  <span className="text-[9px] uppercase tracking-[0.12em] text-[#5cc7eb] font-bold">
                    ✓ GST Included
                  </span>
                </div>
              </>
            ) : (
              /* ── EXCLUSIVE: Subtotal + GST line + Total ── */
              <>
                <div className="mt-3 flex justify-between text-[10px] text-slate-300">
                  <span>Subtotal</span>
                  <span>${previewItemTotal.toFixed(2)}</span>
                </div>
                <div className="mt-1.5 flex justify-between text-[10px] text-slate-400">
                  <span>GST ({taxRateVal}%)</span>
                  <span>+${exclusiveGst.toFixed(2)}</span>
                </div>
                <div className="mt-3 h-px bg-white/10" />
                <div className="mt-3 flex justify-between text-[13px] font-bold text-white">
                  <span>Total</span>
                  <span className="text-[#30b7ff]">${exclusiveTotal.toFixed(2)}</span>
                </div>
              </>
            )}
          </div>
        </div>

        <div className="mt-8 flex items-center justify-end gap-8">
          <button
            type="button"
            onClick={onBack}
            className="text-[13px] font-medium text-slate-600 hover:text-slate-900 transition"
          >
            Back
          </button>
          <button
            type="button"
            onClick={onSkip}
            className="text-[13px] text-slate-700 font-medium hover:text-slate-900 transition"
          >
            Skip for now
          </button>
          <button
            type="button"
            onClick={onNext}
            disabled={!nextEnabled}
            className="h-11 px-8 rounded-full bg-[#07142a] text-white text-[13px] font-semibold shadow-xl shadow-black/20 disabled:opacity-50 disabled:cursor-not-allowed hover:bg-black transition"
            aria-disabled={!nextEnabled}
          >
            Next →
          </button>
        </div>
      </div>
    </section>
  );
}
