export type PermissionMap = Record<string, string[]>;

export type PermissionRole = 'ADMIN' | 'MANAGER' | 'CASHIER' | 'KITCHEN';

export type PermissionGroup =
  | 'BILLING'
  | 'PAYMENTS'
  | 'RECEIPTS'
  | 'KITCHEN'
  | 'CUSTOMERS'
  | 'MENU'
  | 'INVENTORY'
  | 'REPORTS'
  | 'STAFF'
  | 'SETTINGS';

export const FRONTEND_PERMISSIONS = {
  BILLING_CREATE: 'BILLING:CREATE_BILL',
  BILLING_VOID: 'BILLING:VOID_BILL',
  BILLING_DISCOUNT: 'BILLING:APPLY_MANUAL_DISCOUNT',
  BILLING_VIEW_OPEN: 'BILLING:VIEW_ALL_OPEN_BILLS',

  PAYMENTS_CASH: 'PAYMENTS:CASH',
  PAYMENTS_CARD: 'PAYMENTS:CARD',
  PAYMENTS_SPLIT: 'PAYMENTS:SPLIT',
  PAYMENTS_DELIVERY_PAID: 'PAYMENTS:MARK_DELIVERY_AS_PAID',

  RECEIPTS_PRINT: 'RECEIPTS:PRINT_RECEIPT',
  RECEIPTS_SMS: 'RECEIPTS:SEND_SMS_RECEIPT',

  KITCHEN_SEND: 'KITCHEN:SAVE_AND_SEND_TO_KITCHEN',
  KITCHEN_VIEW: 'KITCHEN:VIEW_KITCHEN_DASHBOARD',
  KITCHEN_MARK_READY: 'KITCHEN:MARK_READY',
  KITCHEN_BUMP: 'KITCHEN:BUMP',
  KITCHEN_RECALL: 'KITCHEN:RECALL',

  CUSTOMERS_LOOKUP: 'CUSTOMERS:LOOK_UP_CUSTOMER',
  CUSTOMERS_VIEW_PROFILES: 'CUSTOMERS:VIEW_CUSTOMER_PROFILES',
  CUSTOMERS_VIEW_HISTORY: 'CUSTOMERS:VIEW_PURCHASE_HISTORY',
  CUSTOMERS_ADJUST_LOYALTY: 'CUSTOMERS:ADJUST_LOYALTY_POINTS_MANUALLY',

  MENU_ADD_EDIT_ITEMS: 'MENU:ADD_EDIT_ITEMS',
  MENU_DELETE_ITEMS: 'MENU:DELETE_ITEMS',
  MENU_ADD_EDIT_CATEGORIES: 'MENU:ADD_EDIT_CATEGORIES',
  MENU_DELETE_CATEGORIES: 'MENU:DELETE_CATEGORIES',
  MENU_HIDE_SHOW_ITEMS: 'MENU:HIDE_SHOW_ITEMS',

  INVENTORY_VIEW_STOCK: 'INVENTORY:VIEW_STOCK',
  INVENTORY_ADJUST_STOCK: 'INVENTORY:MANUALLY_ADJUST_STOCK',
  INVENTORY_VIEW_LOW_STOCK: 'INVENTORY:VIEW_LOW_STOCK_ALERTS',

  REPORTS_VIEW: 'REPORTS:VIEW_REPORTS',
  REPORTS_EXPORT: 'REPORTS:EXPORT_REPORTS',

  STAFF_INVITE: 'STAFF:INVITE_STAFF',
  STAFF_EDIT: 'STAFF:EDIT_STAFF',
  STAFF_DEACTIVATE: 'STAFF:DEACTIVATE_STAFF',
  STAFF_DELETE: 'STAFF:DELETE_STAFF',

  SETTINGS_VIEW: 'SETTINGS:VIEW_SETTINGS',
  SETTINGS_EDIT_PROFILE: 'SETTINGS:EDIT_RESTAURANT_PROFILE',
  SETTINGS_EDIT_TAX: 'SETTINGS:EDIT_TAX',
  SETTINGS_EDIT_LOYALTY: 'SETTINGS:EDIT_LOYALTY',
  SETTINGS_TYRO: 'SETTINGS:SET_UP_TYRO',
  SETTINGS_SMS_CREDITS: 'SETTINGS:PURCHASE_SMS_CREDITS',
  SETTINGS_TERMINALS: 'SETTINGS:MANAGE_TERMINALS',
  SETTINGS_CONFIGURE_PERMISSIONS: 'SETTINGS:CONFIGURE_ROLE_PERMISSIONS',
} as const;

export const hasPermissionCode = (
  permissions: PermissionMap | null | undefined,
  code: string,
): boolean => {
  if (!permissions) {
    return false;
  }

  const [group, action] = code.split(':');
  if (!group || !action) {
    return false;
  }

  return (permissions[group] || []).includes(action);
};

export const isGroupEnabled = (
  permissions: PermissionMap | null | undefined,
  group: PermissionGroup,
): boolean => {
  if (!permissions) {
    return false;
  }

  return (permissions[group] || []).length > 0;
};
